import mongoose,{Schema} from "mongoose";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";

const user_schema=new Schema({
    username:{
        type:String,
        require:true,
        unique:true,
        lowercase:true,
        trim:true,
        index:true,//for searching this makes it a bit more optimized
    },
    email:{
        type:String,
        require:true,
        unique:true,
        lowercase:true,
        trim:true,
    },
    full_name:{
        type:String,
        require:true,
        trim:true,
        index:true,
    },
    avatar:{
        type:String,//cloudinary url
        required:true,
    },
    cover_image:{
        type:String,//cloudinary url
    },
    watch_history:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Video",
            default:[]
        }
    ],
    password:{
        type:String,
        required:[true,'password is required']
    },
    refresh_token:{
        type:String
    },
    created_at:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Video"
    },
    updated_at:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Video"
    }
},{timestamps:true})

//.pre is a middleware/hook .. this says tht just before user_schema is saved in db , hash the password if password is changed
user_schema.pre("save",async function (next) {
    if(this.isModified("password")) // only when password is modified , is when u hash it again
    {
        this.password=await bcrypt.hash(this.password,10)
        next()
    }
})

// below is a custom method which we have added into the user_schema which checks if the password is correct everytime user enter the password

user_schema.methods.is_password_correct=async function(password){
    return await bcrypt.compare(password,this.password)
}
user_schema.methods.generate_access_token=function(){
   return jwt.sign(
        {// payload
            username:this.username,  
            fullname:this.fullname,
            _id:this._id, //this id is generated by the mongodb itself
            email:this.email
        },
        //signature
        process.env.ACCESS_TOKEN_SECRET,
        
        {
            expiresIn:process.env.ACCESS_TOKEN_EXPIRY
        }
    )
}
user_schema.methods.generate_refresh_token=function(){
    return jwt.sign(
        {
            _id:this._id
        },
        process.env.REFRESH_TOKEN_SECRET,
        {
            expiresIn:process.env.REFRESH_TOKEN_EXPIRY
        }
    )
}
export const User=mongoose.model("User",user_schema)
